name:                easywordy
version:             0.1.0.0
github:              "whatsupfudd/easywordy"
license:             BSD3
author:              "Hugo DesRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "None."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            software.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/whatsupfudd/easywordy#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - text
  - time
  - vector
  # For Map, ...:
  - containers
  # For HashMap (misc JSON field decoding)
  - unordered-containers

  # For YAML (config file):
  - yaml
  - directory
  - filepath
  # For Git (version):
  - gitrev
  # For options:
  - optparse-applicative
  # For Cont(T):
  - mtl
  # For SQL:
  - postgresql-binary
  - hasql
  - hasql-th
  - hasql-pool
  # For Servant:
  - servant
  - servant-auth
  - servant-auth-server
  - servant-multipart
  - servant-server
  - exceptions
  - warp
  - unix
  # For CORS:
  - wai-cors
  - wai-extra
  - case-insensitive
  - http-types
  # For //, /: of http content types in accept HTML:
  - http-media
  # For urlencoded POST body parsing:
  - http-api-data
  # For HTTP protocol (Wai):
  - wai
  - wai-cors
  - wai-extra
  - streaming-commons
  # For JWT crypto support:
  - jose
  # For JWT crypto support:
  - lens
  - lucid
  - megaparsec
  - mmark
  # Inline C:
  - inline-c
  # MySQL:
  - mysql-haskell
  - io-streams
  # For WebSockets/HTMX:
  - websockets
  - servant-websockets
  - servant-htmx
  # For HTML rendering:
  - blaze-html
  - blaze-htmx
  - blaze-svg
  - blaze-markup
  - markdown
  # For safe exceptions:
  - safe-exceptions
  # For decoding serialized data:
  - binary
  # For inline JS:
  - inline-js
  - inline-js-core
  - rio
  # For app spec:
  - uuid
  # For state management in ws handling loop:
  - mtl
  # For AI:
  - http-client >= 0.7.17
  - http-conduit >= 2.3.8
  - http-client-tls >= 0.3.8
  - connection >= 0.3.2
  # For STM:
  - stm
  # For file watching:
  - fsnotify
  # For scenario support:
  - profunctors
  # For Aox:
  - aoxsup
  # For MinIO:
  - minio-hs
  - scientific
  - conduit
  - unliftio
  #- primitive
  #- memory
  # For Wapps:
  - aoxsup
  - gnuhealth
  - knowdocs
  - scenario
  - z14l
  - complexor


default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- OverloadedRecordDot

ghc-options:
# - -Wall
# - -Wunused-matches
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


library:
  source-dirs: src
  ghc-options:
    - -g

extra-libraries: php

executables:
  easywordy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -g
    dependencies:
    - easywordy

tests:
  easywordy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - easywordy
