resolver:
  # url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/25.yaml
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/44.yaml


packages:
  - .

extra-deps:
  - servant-htmx-0.1.0.2@sha256:cdafd3165d28694ec4bf81fff3b87b4721415293d75a394a97c26d0d4d57e38c,1817
  - blaze-htmx-0.1.0.0@sha256:cfd799bf5e0693879ad175168f6c78d45cb8f543428fa374f6ffb62fbc8dc52f,1327

  - ../Lib/inline-js/inline-js
  - ../Lib/inline-js/inline-js-core
  - ../../../Haskell/OpenAI/LocalLibs/openai-client
  - ../../../Haskell/OpenAI/LocalLibs/openai-client/openai-gen
  - ../../../Haskell/OpenAI/LocalLibs/hs-connection
  - ../../../Haskell/Minio/minio-hs
  - ../Wapp/Lib/Natives/General
  - ../Wapp/Lib/Natives/Aox
  - ../Wapp/Lib/Natives/GnuHealth
  - ../Wapp/Lib/Natives/KnowDocs
  - ../Wapp/Lib/Natives/Scenario
  - ../Wapp/Lib/Natives/Z14L
  - ../Wapp/Lib/Natives/Complexor
  - ../Wapp/Lib/Natives/GoldFann
  - ../Wapp/Lib/Natives/KdofA


system-ghc: true
allow-newer: true

extra-include-dirs:
  [../Lib/php, ../Lib/php/Zend, ../Lib/php/main, ../Lib/php/TSRM]
extra-lib-dirs: [../Lib/php/libs/x86_64-linux]

# Support dynamic libraries:
configure-options:
  "$everything":
    - --enable-shared

#ghc-options:
#  "$locals": -dynamic

